### ISSUE TITLE
[Features] verify & implement `get_category_item_route`

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#10]
Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `get_category_item_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `get_category_item_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

**Comment by KevinVargis** [comment]
I would like to work on this.

**Comment by Pk13055** [comment]
@KevinVargis How's this coming along?

**Comment by KevinVargis** [comment]
Done with implementation. Trying to add validation of item_id. Currently if it isn't ObjectID type, Internal server error is thrown.

**Comment by gsc2001** [comment]
@KevinVargis  you can see code in PR #37 if you wondering on how to check if passed id is in DB and is valid

**Comment by KevinVargis** [comment]
Thank you, I'll look into it.
