### ISSUE TITLE
[Bug] AddItem "reset" button not working

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#101]
**Describe the bug**
Clicking on Reset OR Cancel does not reset or close the sheet

**To Reproduce**
1. Go to Add *
2. Enter some details and try to reset by clicking on reset
3. Try to cancel the form filling by pressing cancel
4. It doesn't work

**Expected behavior**
They should work

**Comment by gsc2001** [comment]
I want to work on this
