### ISSUE TITLE
[Bug] AddItem Stepper 1 next button stays "red" after successful validation as well

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#102]
**Describe the bug**
On filling in the correct details for the first stepper, the next button should turn "red" (as it does in the second stepper), but it is not

**To Reproduce**
1. Add *
2. Fill in the first stepper sucessfully
3. Observe that the "next" button is still red

**Expected behavior**
It should turn green (as is the case in stepper 2)

**Comment by gsc2001** [comment]
Done in #112
