### ISSUE TITLE
[Features] verify & implement `add_item_route`

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#11]
Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `add_item_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `add_item_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

**Comment by gsc2001** [comment]
I would like to work on this

**Comment by gsc2001** [comment]
I have few doubts regarding this. 
- What are the category ids exactly. Like category id for movies is (movie or movies) ? 
- What should be the database name for that paritcular category? Same as category_id?
- Sending a random string in place of category_id in add_item_route does not result in any error. Is it ok? 
- Sending a valid response for movies to add item route with category_id of shows gives no error. Is it ok ?


The last two can be taken care if implementation of front_end is done correctly. If that is the case then last two are not needed

**Comment by Pk13055** [comment]
- the category IDs are:
    - movies
    - shows
    - anime
    - music
    - books
- The database name(s) should be same as `category_id`
- It's not OK, it has to return an error. You can do something like
```python
from ..models.base import CategoryEnum

if category_id not in CategoryEnum:
    return ResponseBase(success=False, error=["Invalid category"])
else:
    # add item to `category_id`-named db
```
- No it is not OK, you have to enfore that.
```python
from ..models.base import CategoryEnum
if Movie.category_id != CategoryEnum.movies:
    return ResponseBase(success=False, data=...)
else:
   # add item successfully
```

No, frontend just implements basic validation. At the end of the day, it is the responsibility of the backend to ensure incorrect data does not end up in the database.

**Comment by gsc2001** [comment]
Ok. For the last one we dont have any `category_id` field in our request model, so i manually check for all the required corresponding to a particular field which i think is not a good way of doing that or we can add a category_id field in the request body.

**Comment by Pk13055** [comment]
The controller for the `add_item_route` is as follows:
```python
@router.post("/{category_id}", response_model=ItemInResponse, dependencies=[Depends(verify_token)], tags=["add"])
async def add_item_route(category_id: str, item: Union[Movie, Anime, Show, Music],
                         db: AsyncIOMotorClient = Depends(get_database)) -> ItemInResponse:
    """Add item to a given category"""
    # TODO add item to db
    return {"success": True}
```

The url itself has the parameter `{category_id}` so you can just use that, that's why it's not part of the request model.

**Comment by gsc2001** [comment]
Also by the method you told  it will return a 200 OK status. Which i dont think is nice. So we can follow something like [this](https://fastapi.tiangolo.com/tutorial/path-params/#predefined-values) from the documention to restrict possible paths.

**Comment by gsc2001** [comment]
> The controller for the `add_item_route` is as follows:
> 
> ```python
> @router.post("/{category_id}", response_model=ItemInResponse, dependencies=[Depends(verify_token)], tags=["add"])
> async def add_item_route(category_id: str, item: Union[Movie, Anime, Show, Music],
>                          db: AsyncIOMotorClient = Depends(get_database)) -> ItemInResponse:
>     """Add item to a given category"""
>     # TODO add item to db
>     return {"success": True}
> ```
> 
> The url itself has the parameter `{category_id}` so you can just use that, that's why it's not part of the request model.

Basically i am saying that if I grab request_id from url i need to manually check for each required component for each category_id . That is if the url is for movies, and request is of the form shows i need to verify from the request body that the object structure is of the type mentioned in the url

**Comment by Pk13055** [comment]
As I had mentioned earlier:
```python
from ..models.base import CategoryEnum
if category_id not in CategoryEnum:
    return ResponseBase(success=False, data=...)
else:
   # here just add a simple if/else
   if category_id == CategoryEnum.movies:
      item = Movie(data)
   # similarly for all else
   # finally add to db
   _res = db[category_id]["data"].insert_one(item.dict())
   return ItemInResponse(data=item)
```

PS: Refer to [this](https://pydantic-docs.helpmanual.io/usage/models/) for details on models and validation

**Comment by gsc2001** [comment]
There are some problems in this. First setting data to elipsis (...) is giving this error. 

![image](https://user-images.githubusercontent.com/56212978/83951145-1c5c9880-a84d-11ea-8715-85b24f721a00.png)

Which i fixed by not passing any value in data.  But the MAJOR problem is that the route expects ItemInResponse model which has data required, but we are sending ResponseBase which has no data, therefore giving this error. 

![image](https://user-images.githubusercontent.com/56212978/83951260-d94ef500-a84d-11ea-84d7-271ed4026219.png)

I tried sending an empty dict with data but that didn't work too ( i expected this ) as it requires different fields required. Resulting into this. 

![image](https://user-images.githubusercontent.com/56212978/83951295-2337db00-a84e-11ea-9c58-f029002f4383.png)

Now i am stuck as i dont know how to send error back. I read the link you send but coudn't take out something fruitful.

**Comment by kjain1810** [comment]
```
from ..models.base import CategoryEnum

if category_id not in CategoryEnum:
    return ResponseBase(success=False, error=["Invalid category"])
else:
    # add item to `category_id`-named db

```
@gsc2001 is this working for you? The if condition always returns true for me as checking ```in CategoryEnum``` gives me objects of type ```CategoryEnum.movie``` , etc. How did you access the values in them?

**Comment by gsc2001** [comment]
@kjain1810  Yeah I realized that just now. The if condition is also not working.   I tried fixing it by casting casting_id to CategoryEnum like this
```python
# just cast category_id to CategoryEnum
category_id = CategoryEnum(category_id)
if category_id not in CategoryEnum:
# now normal
```

But there is a problem in this also as if category_id is not a CategoryEnum it will result into error like this
![image](https://user-images.githubusercontent.com/56212978/83952349-f38cd100-a855-11ea-9feb-d74da2a2c620.png)

All these problems can be fixed if use the method as told in documentation, which I told earlier

**Comment by kjain1810** [comment]
@gsc2001 doesn't that just hard codes the different categories that we have?That'll have issues if we want to expand our category list in the future. There must be a better way for this.

**Comment by gsc2001** [comment]
@kjain1810  are you referring to method in the documentation or in which i told. The method which is in the documentation is very good we can easily add more categories to it without any hassle by adding then in the CategoryEnum class

**Comment by kjain1810** [comment]
@gsc2001 I am unable to understand how the method provided in <a href = "https://fastapi.tiangolo.com/tutorial/path-params/#predefined-values" >these documentations </a> would provide us an easy way to add more categories in the future. However, I tried a couple of methods and found this to be the easiest one: 
```python 
    for x in CategoryEnum:
        if category_id == x.value:
            # do what you have to
    return ItemsInResponse(success = False, error = ["Invalid category!"])
```

**Comment by Pk13055** [comment]
Check this out https://stackoverflow.com/a/29795561

**Comment by Pk13055** [comment]
> @gsc2001 I am unable to understand how the method provided in <a href = "https://fastapi.tiangolo.com/tutorial/path-params/#predefined-values" >these documentations </a> would provide us an easy way to add more categories in the future. However, I tried a couple of methods and found this to be the easiest one: 
> 
> ```python 
> 
>     for x in CategoryEnum:
> 
>         if category_id == x.value:
> 
>             # do what you have to
> 
>     return ItemsInResponse(success = False, error = ["Invalid category!"])
> 
> ```

This is bad practice since a loop is run each time
And you need it to be category agnostic

**Comment by gsc2001** [comment]
So i have figured this out we can send error by raising HTTPException and setting status codes. but initially even if i set 404 status code it sent 200. This could be rectified just by adding status_code in JSONResponse in HTTPException handeler. and convert it to something like this.
```python
async def http_error_handler(request: Request, exc: HTTPException) -> JSONResponse:
    return JSONResponse({"errors": [exc.detail]}, status_code=exc.status_code)
``` 

and raising the HTTPException like this:- 
```python
if category_id not in CategoryEnum.__members__:
        raise HTTPException(status_code=404, detail="Category ID not found")
```
And all of this works pretty well.

**Comment by gsc2001** [comment]
Bson is not able to encode Set of typing. Its showing error as follows
![image](https://user-images.githubusercontent.com/56212978/83963181-9d557780-a8c1-11ea-8bb3-9a7ab78a3530.png)
What can be done . I searched on google and found [this](https://api.mongodb.com/python/current/examples/custom_type.html) but this requires a lot of changes. And also why cant we use simple List in place of Set?

**Comment by Pk13055** [comment]
Okay best option is convert it to a list and use `$addToSet` instead of `$push`

**Comment by gsc2001** [comment]
You mean to use these these while updating ?

**Comment by Pk13055** [comment]
Yes, `$addToSet` will avoid adding new genres if they already exist in the array
