### ISSUE TITLE
[Improvement] UI element for editing should match addition

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#110]
**Is your feature request related to a problem? Please describe.**
Currently the UI for editing the post has different selection elements than the add item post. 

**Describe the solution you'd like**
Update the edit post UI to have the same `input` elements for the various fields.

**Comment by Pk13055** [comment]
@Megha-Bose please start changing the field types to match the add item form. Additionally, the genres have to also be editable

**Comment by Megha-Bose** [comment]
@Pk13055 Okay.
