### ISSUE TITLE
[Addition] cleaned movie database

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#114]
Combine the movielens 25M dataset with the tmdb dataset and coerce it into a `.json` file that can be imported into mongo.
This step needa to be completed for us to be able to test/implement the search API.

**Comment by Pk13055** [comment]
@gsc2001 will work on this

**Comment by gsc2001** [comment]
Ok :+1:

**Comment by gsc2001** [comment]
So do i combine all the data or only which is in our model.?
