### ISSUE TITLE
[Features] verify & implement `update_item_route`

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#12]
Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `update_item_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `update_item_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

**Comment by susiejojo** [comment]
I'd like to work on this.

**Comment by Pk13055** [comment]
Sure, but you'll have to wait for #11 to be merged before working on this. Also, similar sort of checks would be ensured under this route as well.

**Comment by Pk13055** [comment]
@susiejojo You can work on this, since it has been merged. For the most part, this would follow the same structure as the `add_item_route` controller

**Comment by susiejojo** [comment]
On logging in through CAS, I get authenticated as per the logs, but it returns Internal Server Error with the following message in logs:
![image](https://user-images.githubusercontent.com/42820001/83978689-ceb45e80-a926-11ea-9092-ec2d22c0d395.png)
Is the redirect URL on logging in not fixed?

**Comment by Pk13055** [comment]
It should work, try the latest commit

**Comment by susiejojo** [comment]
As pointed by Gurkirat in #32, this needs to be fixed.

**Comment by Pk13055** [comment]
@susiejojo The issue has been fixed by the latest merge. Check it it is fixable now

**Comment by susiejojo** [comment]
So updating will happen by specific fields or by the whole response? We may need to define a schema for ItemInUpdate then right?

**Comment by Pk13055** [comment]
It has to be whole schema, basically once a fetch is done to render the item anyways there will be all the data available.
So modifying a single item will change a part of the `Item` state and then a patch request can be sent to, say, `/api/movies/{ObjectId}` with the entire state
