### ISSUE TITLE
[Features] verify & implement `get_user_route`

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#18]
Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `get_user_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `get_user_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

**Comment by MSurfer20** [comment]
Can this issue be assigned to me

**Comment by Pk13055** [comment]
@MSurfer20 How's this coming along?

**Comment by gsc2001** [comment]
If you are having any problem @MSurfer20  please comment here.

**Comment by MSurfer20** [comment]
I was getting Internal Service Error, I'll fix it by today
