### ISSUE TITLE
[Testing] Backend routes

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#44]
> origin/backend-testing

## Styling and PEP
- [ ] No redundant/extra imports (check which imports are being used in a particular file and remove the ones that aren't)
- [ ] Sorted import order
```python
import [system-package]
# more system imports
<EMPTY LINE>
import [installed-package]
# more installed packages imports
<EMPTY LINE>
import [local-packages]
# more local packages
```
- [ ] Relative imports for local packages

```python
from ..models.responses import Foo
# instead of
from app.models.response import Foo
```

- [ ] Line spacing and EOL
    - Two line spaces between top-level functions/classes
    - One line space at the end of each file
- [ ] Function definition and declaration
    - No space between keyword args and default arguments (`def goo(foo=bar)`)
    - One space between keyword args and default argument if type is specified (`def goo(foo: str = bar)`)

## Code Logic and functionality checks
- Anywhere `category_id` is present, the declaration should be `category_id: CategoryEnum` for proper type handling
- Anywhere `*_id` is used, check two things:
    - [ ] If ID is malformed appropriate error is returned
    - [ ] If object does not exist, is proper error message returned. (ideally, no need to `raise HTTPException` anywhere.

- [ ] Routes function (read: return response) irrespective of success (handle all cases)
- [ ] Repeat trigger of route does not change (changes where necessary)

## Sanity Checks

- [ ] `get_category_route()` verified functionality
- [ ] `get_category_item_route()` verified functionality
- [ ] `add_item_route()` verified functionality
- [ ] `update_item_route()` verified functionality
- [ ] `rate_item_route()` verified functionality
- [ ] `login_route()` verified functionality
- [ ] `get_category_list_route()` verified functionality
- [ ] `get_users_route()` verified functionality
- [ ] `signup_route()` verified functionality
- [ ] `get_user_route()` verified functionality
- [ ] `update_user_route()` verified functionality
- [ ] `like_item_route()` verified functionality

**Comment by gsc2001** [comment]
Sure. @Pk13055

**Comment by gsc2001** [comment]
Styling and pep8 done

**Comment by gsc2001** [comment]
> > origin/backend-testing
> 
> ## Styling and PEP
> * [x]  No redundant/extra imports (check which imports are being used in a particular file and remove the ones that aren't)
> * [x]  Sorted import order
> 
> ```python
> import [system-package]
> # more system imports
> <EMPTY LINE>
> import [installed-package]
> # more installed packages imports
> <EMPTY LINE>
> import [local-packages]
> # more local packages
> ```
> 
> * [x]  Relative imports for local packages
> 
> ```python
> from ..models.responses import Foo
> # instead of
> from app.models.response import Foo
> ```
> 
> * [x]  Line spacing and EOL
>   
>   * Two line spaces between top-level functions/classes
>   * One line space at the end of each file
> * [x]  Function definition and declaration
>   
>   * No space between keyword args and default arguments (`def goo(foo=bar)`)
>   * One space between keyword args and default argument if type is specified (`def goo(foo: str = bar)`)
> 
> ## Code Logic and functionality checks
> * Anywhere `category_id` is present, the declaration should be `category_id: CategoryEnum` for proper type handling
> * Anywhere `*_id` is used, check two things:
>   
>   * [ ]  If ID is malformed appropriate error is returned
>   * [ ]  If object does not exist, is proper error message returned. (ideally, no need to `raise HTTPException` anywhere.
> * [ ]  Routes function (read: return response) irrespective of success (handle all cases)
> * [ ]  Repeat trigger of route does not change (changes where necessary)
> 
> ## Sanity Checks
> * [ ]  `get_category_route()` verified functionality
> * [ ]  `get_category_item_route()` verified functionality
> * [ ]  `add_item_route()` verified functionality
> * [ ]  `update_item_route()` verified functionality
> * [ ]  `rate_item_route()` verified functionality
> * [ ]  `login_route()` verified functionality
> * [ ]  `get_category_list_route()` verified functionality
> * [ ]  `get_users_route()` verified functionality
> * [ ]  `signup_route()` verified functionality
> * [ ]  `get_user_route()` verified functionality
> * [ ]  `update_user_route()` verified functionality
> * [ ]  `like_item_route()` verified functionality

**Comment by gsc2001** [comment]
I used HTTPException where it is required to send data in response. As we dont have data it was not allowing to return only success=False

**Comment by gsc2001** [comment]
@Pk13055  there is an error in update_item route. In order to update an item we need to send all required fields which were set previously because it needs item to be a category type,
we have set item like this
```python
item:Union[Movie, Anime, Show, Music, Book]
```
I am thinking to do this like this
```python
@router.patch("/{category_id}/{item_id}", response_model=ItemInResponse,
              dependencies=[Depends(verify_token)], tags=["update"])
async def update_item_route(category_id: CategoryEnum, item_id: ObjectID,
                            item: dict, db: AsyncIOMotorClient = Depends(get_database)) -> ItemInResponse:
    """Update a given item"""
    classof = {
        CategoryEnum.movies: Movie,
        CategoryEnum.shows: Show,
        CategoryEnum.anime: Anime,
        CategoryEnum.books: Book,
        CategoryEnum.music: Music
    }

    item_keys = set(item.keys())
    class_keys = set(classof[category_id].__fields__.keys())

    # checking if the suplied entities are correct
    if not class_keys.intersection(item_keys) == item_keys:
        raise HTTPException(status_code=400,
                            detail=f'Item does not match {category_id} schema')
    _res = await db[category_id]["data"].find_one_and_update({"_id": item_id}, {"$set": item},
                                                             return_document=ReturnDocument.AFTER)
    return ItemInResponse(data=_res)

**Comment by gsc2001** [comment]
In get user_route in docstring you have written to get the details of the logged in user. but i the route it was getting from user_id passed as param.

So i changed that to this
```python
@router.get("/me", response_model=UserInResponse, tags=["fetch"])
async def get_user_route(token: dict = Depends(verify_token),
                         db: AsyncIOMotorClient = Depends(get_database)) -> UserInResponse:
    """Get user information for logged in user"""
    _user = await db.core.users.find_one(token)
    if _user:
        return UserInResponse(data=_user)
    raise HTTPException(
        status_code=400, detail="User doesn't exist in DB")
```
i added /me because only /api/user it gets clashed with the get categry route as it sees user as a category id

Is it ok @Pk13055

**Comment by gsc2001** [comment]
We dont have any update_user and signup route.

**Comment by gsc2001** [comment]
In the the like item route there were no check if that particular item_id existed. so i updated that to this

```python
async def like_item_route(category_id: CategoryEnum, item_id: ObjectID, like: Like,
                          token: dict = Depends(verify_token),
                          db: AsyncIOMotorClient = Depends(get_database)) -> LikeInResponse:
    """Like a given shared item"""
    _res = await db[category_id]["data"].find_one({"_id": item_id})
    if _res:
        _update = await db.core.users.update_one(token, {
            "$set": {f"likes.{category_id}.{item_id}": like.value}
        })
        return LikeInResponse(data=like, category_id=category_id, item_id=item_id)

    raise HTTPException(
        status_code=400, detail=f'Item id {item_id} not found in {category_id}')
```
this is working perfectly

**Comment by Pk13055** [comment]
> In get user_route in docstring you have written to get the details of the logged in user. but i the route it was getting from user_id passed as param.
> 
> 
> 
> So i changed that to this
> 
> ```python
> 
> @router.get("/me", response_model=UserInResponse, tags=["fetch"])
> 
> async def get_user_route(token: dict = Depends(verify_token),
> 
>                          db: AsyncIOMotorClient = Depends(get_database)) -> UserInResponse:
> 
>     """Get user information for logged in user"""
> 
>     _user = await db.core.users.find_one(token)
> 
>     if _user:
> 
>         return UserInResponse(data=_user)
> 
>     raise HTTPException(
> 
>         status_code=400, detail="User doesn't exist in DB")
> 
> ```
> 
> i added /me because only /api/user it gets clashed with the get categry route as it sees user as a category id
> 
> 
> 
> Is it ok @Pk13055 

It will have prefix as user anyways

**Comment by gsc2001** [comment]
> > In get user_route in docstring you have written to get the details of the logged in user. but i the route it was getting from user_id passed as param.
> > 
> > 
> > 
> > So i changed that to this
> > 
> > ```python
> > 
> > @router.get("/me", response_model=UserInResponse, tags=["fetch"])
> > 
> > async def get_user_route(token: dict = Depends(verify_token),
> > 
> >                          db: AsyncIOMotorClient = Depends(get_database)) -> UserInResponse:
> > 
> >     """Get user information for logged in user"""
> > 
> >     _user = await db.core.users.find_one(token)
> > 
> >     if _user:
> > 
> >         return UserInResponse(data=_user)
> > 
> >     raise HTTPException(
> > 
> >         status_code=400, detail="User doesn't exist in DB")
> > 
> > ```
> > 
> > i added /me because only /api/user it gets clashed with the get categry route as it sees user as a category id
> > 
> > 
> > 
> > Is it ok @Pk13055 
> 
> It will have prefix as user anyways

But now it gets /user/me , no routes clash woth this

**Comment by Pk13055** [comment]
Even with prefix user does it actually clash?

**Comment by gsc2001** [comment]
> @Pk13055  there is an error in update_item route. In order to update an item we need to send all required fields which were set previously because it needs item to be a category type,
> we have set item like this
> ```python
> item:Union[Movie, Anime, Show, Music, Book]
> ```
> I am thinking to do this like this
> ```python
> @router.patch("/{category_id}/{item_id}", response_model=ItemInResponse,
>               dependencies=[Depends(verify_token)], tags=["update"])
> async def update_item_route(category_id: CategoryEnum, item_id: ObjectID,
>                             item:dict, db: AsyncIOMotorClient = Depends(get_database)) -> ItemInResponse:
>     """Update a given item"""
>     classof = {
>         CategoryEnum.movies: Movie,
>         CategoryEnum.shows: Show,
>         CategoryEnum.anime: Anime,
>         CategoryEnum.books: Book,
>         CategoryEnum.music: Music
>     }
> 
>     item_keys = set(item.keys())
>     class_keys = set(classof[category_id].__fields__.keys())
> 
>     # checking if the suplied entities are correct
>     if not class_keys.intersection(item_keys) == item_keys:
>         raise HTTPException(status_code=400,
>                             detail=f'Item does not match {category_id} schema')
>     _res = await db[category_id]["data"].find_one_and_update({"_id": item_id}, {"$set": item},
>                                                              return_document=ReturnDocument.AFTER)
>     return ItemInResponse(data=_res)
> 
> ```
> What do you suggest @Pk13055 

So how do i do this, i am not able to think of any other way

**Comment by Pk13055** [comment]
All fields will be sent since frontend will have original state

**Comment by gsc2001** [comment]
> Even with prefix user does it actually clash?
> 

It clashes when i use /user only , otherwisr its fine

**Comment by gsc2001** [comment]
> All fields will be sent since frontend will have original state

Ok.

**Comment by Pk13055** [comment]
Also try changing the order of the `app.include_router` in `app/__init__.py`. That might fix the route mistmatching

**Comment by gsc2001** [comment]
Yeah, that will fix the issue, so do i use only / to get the current user data. ?

**Comment by gsc2001** [comment]
There is a problem in rate element route. On supplying a valid rating its not working
its showing this error:- 
![image](https://user-images.githubusercontent.com/56212978/84431638-3df0c200-ac49-11ea-8dd5-dac397a98289.png)
On seeing further i found that rating is a list of Dict[CategoryEnum, ..], but when doing 'movies'  its takes as a string. So it gives error. 
![image](https://user-images.githubusercontent.com/56212978/84433508-020b2c00-ac4c-11ea-9933-d492a33e3eeb.png)
 On seeing further, Like is a similar but it uses only str. Therefore it doesn't gives error. So should i use str only ? 
On googling i found we can use TypedDict from typing. But unfortunately it is from python 3.8, and we are using python 3.7.
I am not to find any other way of restricting the keys in dict.

**Comment by gsc2001** [comment]
its wierd its working with like but not here

**Comment by gsc2001** [comment]
Only this is left everything else has been done

**Comment by kjain1810** [comment]
@gsc2001 I also faced the same problem while trying to implement this route. <a href="https://github.com/kjain1810/recommender-portal/blob/rate_item_route-fix/backend/app/categories/controller.py"> This </a> code works but it does not return any data (This is before the definition of ResponseBase was changed). The problem is with the rating being float. Since like was defined as a Like object having values of LikeEnum, this problem did not occur there. Making a similar Rate object with values RateEnum might work?

**Comment by gsc2001** [comment]
> There is a problem in rate element route. On supplying a valid rating its not working
> its showing this error:-
> ![image](https://user-images.githubusercontent.com/56212978/84431638-3df0c200-ac49-11ea-8dd5-dac397a98289.png)
> On seeing further i found that rating is a list of Dict[CategoryEnum, ..], but when doing 'movies' its takes as a string. So it gives error.
> ![image](https://user-images.githubusercontent.com/56212978/84433508-020b2c00-ac4c-11ea-9933-d492a33e3eeb.png)
> On seeing further, Like is a similar but it uses only str. Therefore it doesn't gives error. So should i use str only ?
> On googling i found we can use TypedDict from typing. But unfortunately it is from python 3.8, and we are using python 3.7.
> I am not to find any other way of restricting the keys in dict.
> 
> The error is not this i converted it to str but it still shows this error. Dont know to fix this

Changing to str worked, the problem was after changing i didn't created new user with that
