### ISSUE TITLE
[Bug] Add Post button disappears

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#55]
The FAB for add post disappears on navigating to any of the category pages.

FAB Present on homepage:
![Screenshot from 2020-06-25 17-46-25](https://user-images.githubusercontent.com/13479308/85718193-e7d15380-b70b-11ea-9937-5f6b59f950eb.png)

FAB **NOT** present on anime page:
![Screenshot from 2020-06-25 17-47-37](https://user-images.githubusercontent.com/13479308/85718291-fddf1400-b70b-11ea-9193-8c6c7907b280.png)

## Details

- Using `docker-compose`
- Latest `template` branch

**Comment by Megha-Bose** [comment]
`<v-tooltip left>
        <template #activator="{ on }">
              <v-icon v-on="on">{{ item.icon }}</v-icon>
        </template>
        <span>Add {{ item.title }}</span>
 </v-tooltip>` 

Adding tooltip to v-icon instead of v-btn fixes this.

**Comment by Pk13055** [comment]
@Megha-Bose Okay, is it possible for you to submit a PR for the same?
