### ISSUE TITLE
Verify & Implement Getter: items/getItemsByCategory

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#56]
#### Function to implement:

Getter: items/getItemsByCategory

Things to note:

-   [ ] Ensure different branch for each issue.
-   [ ] Rebase frequently to avoid conflicts later on
-   [ ] Try to ensure only a couple of commits
-   [ ] Test your code thoroughly before pushing
-   [ ] Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   [ ] Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

**Comment by Megha-Bose** [comment]
I would like to take up this issue.

**Comment by MSurfer20** [comment]
I'd be happy to help ya out :)
