### ISSUE TITLE
Verify & Implement Mutation: items/DEL_ITEM

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#57]
#### Function to implement:

Mutation: items/DEL_ITEM

Things to note:

-   [ ] Ensure different branch for each issue.
-   [ ] Rebase frequently to avoid conflicts later on
-   [ ] Try to ensure only a couple of commits
-   [ ] Test your code thoroughly before pushing
-   [ ] Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   [ ] Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

**Comment by tathagata-raha** [comment]
I want to take this issue

**Comment by susiejojo** [comment]
I can help u with this!

**Comment by Pk13055** [comment]
What’s the progress on this issue?

**Comment by Pk13055** [comment]
@tathagata-raha You need to rebase your PR such that it has only 1 commit. @susiejojo see if you can help him with the same
