### ISSUE TITLE
Verify & Implement Action: items/updateItem

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#58]
#### Function to implement:

Action: items/updateItem

Things to note:

-   [ ] Ensure different branch for each issue.
-   [ ] Rebase frequently to avoid conflicts later on
-   [ ] Try to ensure only a couple of commits
-   [ ] Test your code thoroughly before pushing
-   [ ] Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   [ ] Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

**Comment by gsc2001** [comment]
Dependent on #57

**Comment by kjain1810** [comment]
I can work on this

**Comment by gsc2001** [comment]
I am working on this
