### ISSUE TITLE
[UI] Static template site

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#6]
Start looking at the backend API and making the wireframe designs for the various pages. Right off the bat I see a couple of pages:
• Homepage (culmination of all the categories (with recently added content now, probably in the form of a pinterest grid)
• Each category page (A hompage for each category with recently posted content, along with filters depending on model schema)
• Each item homepage (with optional RESTful information pull from APIs (if available))
• User homepage (edit information and collection of their own ratings and likes
• Search page to search for various items (any category) and filter out categories

**Comment by Pk13055** [comment]
You can pull the repo and navigate to `localhost:8000/api/docs` or `localhost:8000/api/redoc` for the documentation of the backend API routes and model schema

**Comment by Pk13055** [comment]
Something like this would be quite nice:
![IMG_0607](https://user-images.githubusercontent.com/13479308/83975271-acafe180-a910-11ea-9a99-207c61a6d36e.PNG)

**Comment by Pk13055** [comment]
@Megha-Bose will be handling this issue

**Comment by Megha-Bose** [comment]
![Screenshot from 2020-06-14 12-17-33](https://user-images.githubusercontent.com/56213000/84587012-4576bd80-ae39-11ea-830e-e7232e2d3ff3.png)
![Screenshot from 2020-06-14 12-17-12](https://user-images.githubusercontent.com/56213000/84587013-49a2db00-ae39-11ea-89da-0266886898b0.png)
![Screenshot from 2020-06-14 12-16-28](https://user-images.githubusercontent.com/56213000/84587020-4c9dcb80-ae39-11ea-8ef8-346681f403a1.png)

**Comment by Pk13055** [comment]
Looks awesome, will check it out myself. In the meanwhile can you just create a PR so we can review it there.
