### ISSUE TITLE
Verify & Implement Mutation: likes/DEL_LIKE

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#60]
#### Function to implement:

Mutation: likes/DEL_LIKE

Things to note:

-   [ ] Ensure different branch for each issue.
-   [ ] Rebase frequently to avoid conflicts later on
-   [ ] Try to ensure only a couple of commits
-   [ ] Test your code thoroughly before pushing
-   [ ] Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   [ ] Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

**Comment by RajWorking** [comment]
i want to work on this

**Comment by kjain1810** [comment]
I can help you with this :)
