### ISSUE TITLE
Verify & Implement Action: likes/upsertLike

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#61]
#### Function to implement:

Action: likes/upsertLike

Things to note:

-   [ ] Ensure different branch for each issue.
-   [ ] Rebase frequently to avoid conflicts later on
-   [ ] Try to ensure only a couple of commits
-   [ ] Test your code thoroughly before pushing
-   [ ] Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   [ ] Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

**Comment by gsc2001** [comment]
Dependent on #60 , #59

**Comment by kjain1810** [comment]
I can work on this if no one from the front end team is

**Comment by Pk13055** [comment]
Sure, go ahead!
