### ISSUE TITLE
Integrate Like Item

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#75]
#### Description

TODO has been added for place to add @ click, create a method for adding/updating the like using likes/upsertLike action. The action will update the like if its already there

Things to note:

-   Ensure different branch for each issue.
-   Rebase frequently to avoid conflicts later on
-   Try to ensure only a couple of commits
-   Test your code thoroughly before pushing
-   Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

**Comment by gsc2001** [comment]
Dependent on #61

**Comment by kush-garg** [comment]
I want to take this.

**Comment by gsc2001** [comment]
@kush-garg do #61 first. It is dependent on that

**Comment by kush-garg** [comment]
I think @kjain1810 is doing that. I am quite confused about how upsert will work. but I can try to write the event part till then.

**Comment by kush-garg** [comment]
Can I start this?

**Comment by kjain1810** [comment]
@kush-garg upsertLike has been merged and the Blocked tag has been removed, I think you can start this

**Comment by Pk13055** [comment]
@kush-garg Have you made any progress so far?

**Comment by kush-garg** [comment]
@Pk13055 I will try to finish this by tonight.
