### ISSUE TITLE
Integrate Rate Item

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#76]
#### Description

TODO has been added for place to add @ click, create a method for adding/updating the rating using ratings/upsertRating action. The action\will update the rating if its already there

Things to note:

-   Ensure different branch for each issue.
-   Rebase frequently to avoid conflicts later on
-   Try to ensure only a couple of commits
-   Test your code thoroughly before pushing
-   Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

**Comment by gsc2001** [comment]
Dependent on #64

**Comment by RajWorking** [comment]
i would like to work on this

**Comment by gsc2001** [comment]
Sure :+1:
