### ISSUE TITLE
Integrate Display each property at appropriate location

### ISSUE THREAD

**Issue by gsc2001** [OSDG-IIITH/recommender-portal#77]
#### Description

Post is taken from global state using id passed, its schema can be seen from localhost:8000/api/redoc

Things to note:

-   Ensure different branch for each issue.
-   Rebase frequently to avoid conflicts later on
-   Try to ensure only a couple of commits
-   Test your code thoroughly before pushing
-   Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

**Comment by Megha-Bose** [comment]
I want to take this.

**Comment by gsc2001** [comment]
Sure :+1:
