### ISSUE TITLE
[Features] verify & implement `get_category_route`

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#9]
Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `get_category_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

Things to note:
    - [ ] Ensure feature branch created with [Features] verify & implement `get_category_route`: `route-fix`, so eg: `get_category_route-fix`
    - [ ] Rebase frequently to avoid conflicts later on
    - [ ] Try to ensure only a couple of commits
    - [ ] Test your code thoroughly before pushing
    - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

Final merge request will be of

> Merge `route-fix` of [username]/recommender-portal into OSDG-IIITH/recommender-portal

**Comment by kjain1810** [comment]
I can work on this

**Comment by kjain1810** [comment]
Should I add validation for the data I am getting or can I assume that the file returned by the database will have the content according to our schemas specified in the documentation?

**Comment by Pk13055** [comment]
@kjain1810 Did you even bother reading the description of this issue? It clearly says to submit the request for 

> Things to note:
> - [ ] Ensure feature branch created with [Features] verify & implement `get_category_route`: `route-fix`, so eg: `get_category_route-fix`
> - [ ] Rebase frequently to avoid conflicts later on
> - [ ] Try to ensure only a couple of commits
> - [ ] Test your code thoroughly before pushing
> - [ ] Add to description, "Fixes #issue-no, eg: Fixes #8 (where #8 is the issue id)"

1. Create a separate branch for the fix (otherwise as you can see on your current PR, there are all the previous commits from the previous merge request being committed again)
2. Add to your **description**, fixes <issue> **NOT** to the title.

**Comment by kjain1810** [comment]
@Pk13055 ohh crap, I thought we had to merge it back before making a pull request, I'll fix and make the request properly, sorry.
