### ISSUE TITLE
[Bug] addition of rating not working

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#95]
**Describe the bug**
once a rating has been added the first time, any subsequent changes to the rating do not reflect in the backend.

**To Reproduce**
1. Create a new item
2. Rate the item
3. Try rating it again
4. See the database (no changes after first addition)

**Expected behavior**
Rating should change each time it is modified

**Comment by gsc2001** [comment]
I am working on it
