### ISSUE TITLE
[Bug] items not displaying without hard refresh

### ISSUE THREAD

**Issue by Pk13055** [OSDG-IIITH/recommender-portal#96]
**Describe the bug**
When you switch to a different category for the first time, the items do not display. A hard refresh (ctrl + shift + r) needs to be done in order to display them.

**To Reproduce**
1. Go to any category
2. Add an item
3. Go to another category
4. Hard refresh (ctrl + shift + r)
5. Navigate to the previous category (in which you added a new item)
6. The item does not show up

**Expected behavior**
The items should show up irrespective of when they are added, and whether the page has been hard refreshed

**Comment by gsc2001** [comment]
I am working on it.

**Comment by gsc2001** [comment]
The basic problem in this was basically that it was loading in back but was not showing anything on front
